// Offline cache for the web game. Generated by tool/build_web.sh: the
// placeholders below are replaced with the build's file list and hash.
//
// - install: precache the app shell (everything except the large CanvasKit
//   variants), then the page reports which CanvasKit variant it loaded and
//   that is cached too (message "cache").
// - fetch: cache first (works offline), network fallback + runtime caching.
//   Only same-origin GETs under this folder; remote config / word list
//   requests go straight to the network (the app caches those itself).
// - a new build changes this file → new cache, old one deleted.
const VERSION = '0c35d6a3ef24';
const PRECACHE = [
  "./",
  "assets/AssetManifest.bin",
  "assets/AssetManifest.bin.json",
  "assets/FontManifest.json",
  "assets/NOTICES",
  "assets/assets/config/default_config.json",
  "assets/assets/fonts/EmojiSubset.ttf",
  "assets/assets/fonts/Vazirmatn-Black.ttf",
  "assets/assets/fonts/Vazirmatn-Bold.ttf",
  "assets/assets/fonts/Vazirmatn-Regular.ttf",
  "assets/assets/sounds/correct.wav",
  "assets/assets/sounds/count.wav",
  "assets/assets/sounds/go.wav",
  "assets/assets/sounds/pass.wav",
  "assets/assets/sounds/round_end.wav",
  "assets/assets/sounds/tick.wav",
  "assets/assets/sounds/win.wav",
  "assets/assets/words/words_ar.json",
  "assets/assets/words/words_en.json",
  "assets/assets/words/words_fa.json",
  "assets/fonts/MaterialIcons-Regular.otf",
  "assets/fonts/fallback/Roboto-Regular.ttf",
  "assets/packages/wakelock_plus/assets/no_sleep.js",
  "assets/shaders/ink_sparkle.frag",
  "assets/shaders/stretch_effect.frag",
  "favicon.png",
  "flutter.js",
  "flutter_bootstrap.js",
  "icons/Icon-192.png",
  "icons/Icon-512.png",
  "icons/Icon-maskable-192.png",
  "icons/Icon-maskable-512.png",
  "main.dart.js",
  "manifest.json",
  "version.json"
];
const CACHE = `pantomime-${VERSION}`;
const SCOPE = new URL('./', self.location).href;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((u) => new Request(new URL(u, SCOPE), { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('pantomime-') && k !== CACHE).map((k) => caches.delete(k)),
      ))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'cache' || !Array.isArray(event.data.urls)) return;
  const urls = event.data.urls.filter((u) => typeof u === 'string' && u.startsWith(SCOPE));
  event.waitUntil(
    caches.open(CACHE).then((cache) => Promise.all(urls.map(async (u) => {
      if (!(await cache.match(u, { ignoreSearch: true }))) await cache.add(u).catch(() => {});
    }))),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || !req.url.startsWith(SCOPE)) return;
  const isPage = req.mode === 'navigate';
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const key = isPage ? new URL('index.html', SCOPE).href : req;
    const hit = await cache.match(key, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res.ok && res.type === 'basic' && !isPage) cache.put(req, res.clone());
      return res;
    } catch (e) {
      if (isPage) {
        const shell = await cache.match(key);
        if (shell) return shell;
      }
      throw e;
    }
  })());
});
